version: "3.2"
services:
  fetcher:
    build: .
    links:
      - "testserver"

  testserver:
    image: kennethreitz/httpbin@sha256:18b93fda4cdd5fd420abe6b60ee6e025022ec21e263eedf62828957a71d09193
