version: "2.3"
services:
  fetcher:
    build: fetcher
    links:
      - "browser"
    environment:
      - CHROMIUM_DEBUGGER_ADDRESS=browser

  browser:
    build: browser
    environment:
      - USER_AGENT=Mozilla/5.0 MyBot
