version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: build image
          command: |
            docker-compose build
      - run:
          name: run tests
          command: |
            docker-compose run -T --rm fetcher testserver/json > /dev/null
            docker-compose run -T --rm fetcher testserver/html > /dev/null
            docker-compose run -T --rm fetcher testserver/robots.txt > /dev/null
            docker-compose run -T --rm fetcher testserver/image/jpeg > /dev/null
            docker-compose run -T --rm fetcher testserver/image/png > /dev/null
            docker-compose run -T --rm fetcher testserver/image/svg > /dev/null
            docker-compose run -T --rm fetcher testserver/image/webp > /dev/null
