version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: build image
          command: |
            set -eu
            docker-compose build
      - run:
          name: run tests
          command: |
            set -eu
            docker-compose run -T --rm rendering-proxy cli testserver/json > /dev/null
            docker-compose run -T --rm rendering-proxy cli testserver/html > /dev/null
            docker-compose run -T --rm rendering-proxy cli testserver/robots.txt > /dev/null
            docker-compose run -T --rm rendering-proxy cli testserver/image/jpeg > /dev/null
            docker-compose run -T --rm rendering-proxy cli testserver/image/png > /dev/null
            docker-compose run -T --rm rendering-proxy cli testserver/image/svg > /dev/null
            docker-compose run -T --rm rendering-proxy cli testserver/image/webp > /dev/null
            docker-compose up -d
            container=$(docker-compose ps -q rendering-proxy)
            docker-compose run -T --rm testcurl -s -o /dev/null http://rendering-proxy:8080/http://testserver/json
            docker-compose run -T --rm testcurl -s -o /dev/null http://rendering-proxy:8080/http://testserver/html
            docker-compose run -T --rm testcurl -s -o /dev/null http://rendering-proxy:8080/http://testserver/robots.txt
            docker-compose run -T --rm testcurl -s -o /dev/null http://rendering-proxy:8080/http://testserver/image/jpeg
            docker-compose run -T --rm testcurl -s -o /dev/null http://rendering-proxy:8080/http://testserver/image/png
            docker-compose run -T --rm testcurl -s -o /dev/null http://rendering-proxy:8080/http://testserver/image/svg
            docker-compose run -T --rm testcurl -s -o /dev/null http://rendering-proxy:8080/http://testserver/image/webp
